" vimrc
" @author dogfooter
" @email dogfooter219@gmail.com
"
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" set shell=/bin/zsh

"My Custom Installed Plugins
" Plugin with vim-plug
call plug#begin('~/.vim/plugged')

" basic
Plug 'scrooloose/nerdtree'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all'  }
Plug 'MarcWeber/vim-addon-mw-utils'
Plug 'tomtom/tlib_vim'
Plug 'jiangmiao/auto-pairs'
Plug 'tpope/vim-surround'
Plug 'vim-scripts/tComment'
Plug 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim/'}
" Plug 'vim-syntastic/syntastic'

"
" Web
Plug 'mattn/emmet-vim'
Plug 'leafgarland/typescript-vim'
Plug 'magarcia/vim-angular2-snippets'
Plug 'garbas/vim-snipmate'
Plug 'honza/vim-snippets'
Plug 'pangloss/vim-javascript'
Plug 'jelera/vim-javascript-syntax', {'for': ['.js']}

" Vue
Plug 'posva/vim-vue'

"
" python
Plug 'davidhalter/jedi-vim' " for python autocomplete
Plug 'nvie/vim-flake8'

" 
" Golang
" Plug 'fatih/vim-go'
" 
" option (not for other's PC)
" Plug 'Valloric/YouCompleteMe' 
Plug 'Shougo/neocomplete.vim'

" Scala

" Git
" Plug 'airblade/vim-gitgutter'

" theme
Plug 'dracula/vim'

" my-own
Plug 'dogfooter/FIP.vim'


call plug#end()
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

"Editor Setting

set bs=2 " for delete with backspace 
set nocompatible " only vIM
set autoindent
set cindent
set smartindent 
set number
set relativenumber 
let python_highlight_all=1
syntax on
set background=light
" set background=dark
" colorscheme solarized
" color dracula
" colorscheme Tomorrow-Night
set ts=4
set shiftwidth=4
set expandtab 
set hlsearch
set ignorecase

set t_Co=256

" for ignore mouse
set mouse=

" start with end of work
" https://medium.com/sunhyoups-story/vim-%EC%97%90%EB%94%94%ED%84%B0-%EC%9D%B4%EC%81%98%EA%B2%8C-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0-5b6b8d546017#.m38vbbsy0
au BufReadPost *
            \ if line("'\"") > 0 && line("'\"") <= line("$") |
            \ exe "norm g`\"" |
            \ endif


" current Cursor line highlight
" set cursorline
" hi cursorline cterm=none ctermbg=Black
" autocmd InsertEnter * highlight  CursorLine cterm=none ctermbg=Black 
" autocmd InsertLeave * highlight  CursorLine cterm=none ctermbg=Black 

let g:user_emmet_expandabbr_key = '<c-e>'


set laststatus=2
set statusline=\ %<%l:%v\ [%P]%=%a\ %h%m%r\ %F\
set visualbell
set t_vb=
set foldmethod=syntax  
set nofoldenable

" for omni completion file
" set autochdir

set noimd
set imi=1

filetype indent on
filetype plugin indent on 

autocmd FileType jade setlocal ts=2 sw=2

if has("mac") || has("macunix")
    set guifont=Monaco\ for\ Powerline:h24
elseif has("win32") || has("win64")
    set guifont=Monaco\ for\ Powerline:h14:cANSI
    set renderoptions=type:directx,renmode:5
endif

" set for vim-javascript 
let g:javascript_plugin_jsdoc = 1

" pep8 flake8
let g:flake8_cmd="/Library/Frameworks/Python.framework/Versions/2.7/bin/flake8"
let g:flake8_show_in_file=1   " show
let g:flake8_max_markers=500  " maximum # of markers to show(500 is default)
" autocmd BufWritePost *.py call Flake8()

" neo complete
" Disable AutoComplPop.
let g:acp_enableAtStartup = 0
" Use neocomplete.
let g:neocomplete#enable_at_startup = 1
" Use smartcase.
let g:neocomplete#enable_smart_case = 1
" Set minimum syntax keyword length.
let g:neocomplete#sources#syntax#min_keyword_length = 3

" Define dictionary.
let g:neocomplete#sources#dictionary#dictionaries = {
    \ 'default' : '',
    \ 'vimshell' : $HOME.'/.vimshell_hist',
    \ 'scheme' : $HOME.'/.gosh_completions'
        \ }

" Define keyword.
if !exists('g:neocomplete#keyword_patterns')
    let g:neocomplete#keyword_patterns = {}
endif
let g:neocomplete#keyword_patterns['default'] = '\h\w*'

" git-gutter
let g:gitgutter_realtime = 0

" Plugin key-mappings.
inoremap <expr><C-g>     neocomplete#undo_completion()
inoremap <expr><C-l>     neocomplete#complete_common_string()

" Recommended key-mappings.
" <CR>: close popup and save indent.
inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
function! s:my_cr_function()
  return (pumvisible() ? "\<C-y>" : "" ) . "\<CR>"
  " For no inserting <CR> key.
  "return pumvisible() ? "\<C-y>" : "\<CR>"
endfunction
" <TAB>: completion.
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
" <C-h>, <BS>: close popup and delete backword char.
inoremap <expr><C-h> neocomplete#smart_close_popup()."\<C-h>"
inoremap <expr><BS> neocomplete#smart_close_popup()."\<C-h>"
" Close popup by <Space>.
"inoremap <expr><Space> pumvisible() ? "\<C-y>" : "\<Space>"

" AutoComplPop like behavior.
"let g:neocomplete#enable_auto_select = 1

" Shell like behavior(not recommended).
"set completeopt+=longest
"let g:neocomplete#enable_auto_select = 1
"let g:neocomplete#disable_auto_complete = 1
"inoremap <expr><TAB>  pumvisible() ? "\<Down>" : "\<C-x>\<C-u>"

" Enable omni completion.
autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags


" crontab vim enable
au FileType crontab setlocal bkc=yes

au FileType yaml setl sw=2 sts=2 et

"" for tag list"
" let Tlist_Use_Right_Window  =1

" ctags tag
set tags=tags

"split navigations
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H> 

"" my custom shortcut
nnoremap <F4> gg v G =
nnoremap <C-o><C-o> :NERDTreeToggle<CR>
nnoremap <C-o><C-f> :FZF<CR>

" for convinience
nnoremap ; :

command! Wq :wq
command! W :w
command! Q :q


function! s:buflist()
  redir => ls
  silent ls
  redir END
  return split(ls, '\n')
endfunction

function! s:bufopen(e)
  execute 'buffer' matchstr(a:e, '^[ 0-9]*')
endfunction

nnoremap <silent> <Leader><Enter> :call fzf#run({
\   'source':  reverse(<sid>buflist()),
\   'sink':    function('<sid>bufopen'),
\   'options': '+m',
\   'down':    len(<sid>buflist()) + 2
\ })<CR>
