# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

ZSH_DISABLE_COMPFIX="true"
export ZSH=/Users/dogfooter/.oh-my-zsh 
export HOME=/Users/dogfooter

# export DRACULA_THEME=/Users/dogfooter/Public/dracula
export OH_MY_ZSH=/Users/dogfooter/.oh-my-zsh
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

export EDITOR=/usr/local/bin/vim 
export TERM="xterm-256color"

export ZSHRC=/Users/dogfooter/.zshrc
export VIMRC=/Users/dogfooter/.vimrc

export DOTFILES=~/playground/dotfiles

# ZSH_THEME="robbyrussell"
ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(
    git
    # svn 
    # zsh-syntax-highlighting
) 
source $ZSH/oh-my-zsh.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# pip should only run if there is a virtualenv currently activated
# export PIP_REQUIRE_VIRTUALENV=true
# cache pip-installed packages to avoid re-downloading
export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache

# global pip
syspip(){
    PIP_REQUIRE_VIRTUALENV="" pip "$@"
}

chrome() {
    open -a "/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome" "$1"
}

fode() {
    code `fzf`
}

fim() {
    vim `fzf`
}

fkill() {
    kill $(ps ax | fzf | awk {'print $1'})
}
alias gs='git status'
alias gl='git log --all --graph --decorate --abbrev-commit'
alias vi='vim'

alias mp3dl='youtube-dl --extract-audio --audio-format mp3'

# pretty json
alias prettyJSON='python -m json.tool'

# ls fzf preview
alias pzp='ls | fzf --preview "cat {}"'

# zshrc change
# alias edit-zsh='vim $DOTFILES/zsh/zshrc&&cp $DOTFILES/zsh/zshrc ~/.zshrc;source ~/.zshrc'

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"


export LC_ALL=ko_KR.UTF-8

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
